### ISSUE TITLE
somebody help newbie

### ISSUE THREAD

**Issue by alpahca** [PacktPublishing/Linux-Kernel-Debugging#2]
I was passedFigure 1.3 – Partial screenshot – truncated output from the kconfig-hardened-check script
(Billimoria, Kaiwan N. Linux Kernel Debugging: Leverage proven tools and advanced techniques to effectively debug Linux kernels and kernel modules (p. 61). Packt Publishing. Kindle Edition. )

And back that part because config.gz.

So i try but

$bin/kconfig-hardened-check -p X86_64 -c ~/lkd_kernels/kconfig.prod01
[!] ERROR: --config and --print can't be used together

i now if i passed that will be problen about modprobe configs affter setting.
please somebody help me

**Comment by alpahca** [comment]
~/lkd_kernels/kconfig_prod01$ ls -l .config
-rw-rw-r-- 1 ked ked 158079  9월 24 23:33 .config

Try just use only -c option unfortunately

ked@ked-VirtualBox:~/lkd_kernels/kconfig_prod01$ '/home/ked/kconfig-hardened-check/bin/kconfig-hardened-check' -c '/home/ked/lkd_kernels/kconfig_prod01' 
[+] Kconfig file to check: /home/ked/lkd_kernels/kconfig_prod01
Traceback (most recent call last):
  File "/home/ked/kconfig-hardened-check/bin/kconfig-hardened-check", line 16, in <module>
    kconfig_hardened_check.main()
  File "/home/ked/kconfig-hardened-check/kconfig_hardened_check/__init__.py", line 976, in main
    arch, msg = detect_arch(args.config, supported_archs)
  File "/home/ked/kconfig-hardened-check/kconfig_hardened_check/__init__.py", line 275, in detect_arch
    with open(fname, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/ked/lkd_kernels/kconfig_prod01'

**Comment by kaiwan** [comment]
Thank you @alpahca .
You're correct, it is a typo / error; pl use EITHER -p or -c option at a time...
F.e.:
bin/kconfig-hardened-check  -c ~/lkd_src/ch1/kconfig_prod01
[...]

It auto-detects the arch (X86_64 here) and generates info on the provided config file..

**Comment by alpahca** [comment]
Your welcome Dr.
Actually I got probelm about setting chap 1 but use the other way.
​
So if you don't mind me asking can you give or upload about chap1 setting iso replica(in my case is virtuall machine)?

It's okay can't about it.
But just want make sure and want dig more kernels with sure space.
Because i'm stupid newbie lol
​

**Comment by alpahca** [comment]
Your welcome Dr.
Actually I got probelm about setting chap 1 but use the other way.
​
So if you don't mind me asking can you give or upload about chap1 setting iso replica(in my case is virtuall machine)?

It's okay can't about it.
But just want make sure and want dig more kernels with sure space.
Because i'm stupid newbie lol

**Comment by alpahca** [comment]
[+] Config check is finished: 'OK' - 104 / 'FAIL' - 73
ked@ked-VirtualBox:~/lkd_kernels/debugk/linux-5.10.60$ make -j8 all
  SYNC    include/config/auto.conf.cmd

*** Error during sync of the configuration.

make[2]: *** [scripts/kconfig/Makefile:71: syncconfig] Error 1
make[1]: *** [Makefile:603: syncconfig] Error 2
make: *** [Makefile:712: include/config/auto.conf.cmd] Error 2
make: *** Deleting file 'include/config/auto.conf.cmd'

i got like this problem

**Comment by kaiwan** [comment]
I see that the make failed..
Seems like a config issue. Pl try these steps:

1. cd <kernel-src-tree>
2. make mrproper              # will del all including .config !
3. lsmod > lsmod.this
4. make LSMOD=lsmod.this localmodconfig       # generates the .config based on your current modules
5. make -j4             # builds the kernel & any modules
6. ...  

Pl try this & let me know.. thanks

**Comment by alpahca** [comment]
ked@ked-VirtualBox:~/lkd_kernels/debugk/linux-5.10.60$ make LSMOD=lsmod.this localmodconfig # generates the .config based on your current modules
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
using config: '/boot/config-5.10.60'
module ipmi_devintf did not have configs CONFIG_IPMI_DEVICE_INTERFACE
module isofs did not have configs CONFIG_ISO9660_FS
module nls_iso8859_1 did not have configs CONFIG_NLS_ISO8859_1
module ipmi_msghandler did not have configs CONFIG_IPMI_HANDLER
module binfmt_misc did not have configs CONFIG_BINFMT_MISC
#
# configuration written to .config
#...

I responed this but the other thing work well!
Thank you!! Dr Kaiwan.

**Comment by alpahca** [comment]
Dr.

when i use

$ make V=1
[...]
/bin/sh: 1: scripts/mod/modpost: not found
make[2]: *** [scripts/Makefile.modpost:124: /home/ked/Linux-Kernel-Debugging-main/ch3/printk_loglevels/Module.symvers] Error 127
make[1]: *** [Makefile:1726: modules] Error 2
make[1]: Leaving directory '/home/ked/lkd_kernels/debugk/linux-5.10.60'
make: *** [Makefile:103: all] Error 2

And I can't found ./printk_loglevels.ko
what should I do??

**Comment by alpahca** [comment]
Hello Mr.Kaiwan.
I folloew Figure 3.5 part.
(Billimoria, Kaiwan N. Linux Kernel Debugging: Leverage proven tools and advanced techniques to effectively debug Linux kernels and kernel modules (p. 166). Packt Publishing. Kindle Edition. )

Is that locate is ~/Debug/linux~/miscdrv_rdwr ? or ch3/miscdrv_rdwr?
I tried both and found /proc/dynamic_debug/control file too but when use ../../lkm miscdrv_rdwr..
(Alredy done the other setting)
Just didnt work :p 

root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ls
Makefile  miscdrv_rdwr.c  rdwr_test_secret.c
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ../../ lkm miscdrv_rdwr
bash: ../../: Is a directory
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# lkm miscdrv_rdwr

Command 'lkm' not found, did you mean:

  command 'lkvm' from deb kvmtool (0.20170904-1)
..

**Comment by kaiwan** [comment]
Hi @alpahca,

Pl see my replies inline below..

On Thu, Oct 6, 2022 at 8:43 PM alpahca ***@***.***> wrote:
>
> Hello Mr.Kaiwan.
> I folloew Figure 3.5 part.
> (Billimoria, Kaiwan N. Linux Kernel Debugging: Leverage proven tools and advanced techniques to effectively debug Linux kernels and kernel modules (p. 166). Packt Publishing. Kindle Edition. )
>
> Is that locate is /Debug/linux/miscdrv_rdwr ? or ch3/miscdrv_rdwr?
> I tried both and found /proc/dynamic_debug/control file too but when use ../../lkm miscdrv_rdwr..
> (Alredy done the other setting)
> Just didnt work :p
>
> ***@***.***:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ls
> Makefile miscdrv_rdwr.c rdwr_test_secret.c
> ***@***.***:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ../../ lkm miscdrv_rdwr
> bash: ../../: Is a directory

There's no space between the ../../ and lkm; it should be as in Figure 3.5:
../../lkm miscdrv_rdwr

Then it will work.

> ***@***.***:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# lkm miscdrv_rdwr
>
> Command 'lkm' not found, did you mean:

To use it like  this, the dir where the 'lkm' script is needs to be in
the PATH env variable.. as it isn't you get this message..

I suggest you spend some time learning Linux command-line basics
properly as well... Thanks.

**Comment by alpahca** [comment]
Thank you Mr.Kaiwan!
Yeah I need to more learn and practice more about Linux command-line basic, right.
I feel that too and I will.

Actually I want to learn about dissamble kernel on machine code or assembly langgue.
So i try to many way patch or diassamle ,that's make kernel taint.

There's some more way for diassamle kernel?

**Comment by kaiwan** [comment]
Try this link:
https://dev.to/offlinemark/how-to-set-up-an-arm64-playground-on-ubuntu-18-04-27i6

**Comment by alpahca** [comment]
Really thanks full teach, advice.
I don't know how much time need for mastering this area.
But wish want be know well.
That mean I'm really respect you, Mr.Kaiwan.
thx for teach newbie well
:)

**Comment by alpahca** [comment]
Ah Mr.
i got problem about this.

root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ls
Makefile  miscdrv_rdwr.c  rdwr_test_secret.c
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ../../lkm miscdrv_rdwr
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# rmmod miscdrv_rdwr 2>/dev/null
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# sudo dmesg -C
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# make | exit 1
strip: './miscdrv_rdwr.ko': No such file
make: *** [Makefile:99: all] Broken pipe

root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# make
strip: './miscdrv_rdwr.ko': No such file

--- Building : KDIR=/lib/modules/5.10.60-prod01/build ARCH= CROSS_COMPILE= ccflags-y=-UDEBUG -DDYNAMIC_DEBUG_MODULE ---
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

make -C /lib/modules/5.10.60-prod01/build M=/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr modules
make[1]: Entering directory '/home/ked/lkd_kernels/debugk/linux-5.10.60'
  CC [M]  /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.o
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c: In function ‘open_miscdrv_rdwr’:
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c:97:2: error: implicit declaration of function ‘PRINT_CTX’ [-Werror=implicit-function-declaration]
   97 |  PRINT_CTX(); // displays process (or atomic) context info
      |  ^~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:280: /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.o] Error 1
make[1]: *** [Makefile:1822: /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr] Error 2
make[1]: Leaving directory '/home/ked/lkd_kernels/debugk/linux-5.10.60'
make: *** [Makefile:103: all] Error 2

I been setting CONFIG_DEBUG_FS_DISALLOW_MOUNT=y

should I refresh ch3/miscdrv_rdwr?

**Comment by alpahca** [comment]
Ah and I buy too kernel programing and...

root@ked-VirtualBox:/home/ked# lsmod > /tmp/lsmod.now
bash: /tmp/lsmod.now: Permission denied
root@ked-VirtualBox:/home/ked# chmod 755 /tmp/lsmod.now
root@ked-VirtualBox:/home/ked# lsmod > /tmp/lsmod.now
bash: /tmp/lsmod.now: Permission denied
root@ked-VirtualBox:/home/ked# cd ..
root@ked-VirtualBox:/home# cd ..
root@ked-VirtualBox:/# chmod 755 /tmp/lsmod.now
root@ked-VirtualBox:/# cp /boot/config-5.6.10-48-generic ${LLKD_KSRC}/.config
cp: cannot stat '/boot/config-5.6.10-48-generic': No such file or directory
root@ked-VirtualBox:/# cp '/boot/config-5.15.0-48-generic'  ${LLKD_KSRC}/.config
root@ked-VirtualBox:/# lsmod > /tmp/lsmod.now
bash: /tmp/lsmod.now: Permission denied
root@ked-VirtualBox:/# sudo bash -c 'cat >> /tmp/lsmod.now'
bash: /tmp/lsmod.now: Permission denied
 
That happen for me.
?.?

**Comment by kaiwan** [comment]
Am unsure why lsmod writing into a temp file as root is failing...
Pl shutdown and restart your VM, then retry..

Also, you're copying exactly from the book; the kernel ver there may
be 5.6.10-48-generic but on your more recent VM it is likely different.
Use /boot/config-$(uname -r) to use your kernel ver...

**Comment by alpahca** [comment]
root@ked-VirtualBox:/home/ked# cp /boot/config-$(uname -r) ${LLKD_KSRC}/.config
root@ked-VirtualBox:/home/ked# lsmod > /tmp/lsmod.now
root@ked-VirtualBox:/home/ked# cd ${LLKD_KSRC}
root@ked-VirtualBox:~# ls
lsmod.this  snap
root@ked-VirtualBox:~# ls /.config
/.config
root@ked-VirtualBox:~# make LSMOD=/tmp/lsmod.now localmodconfig
make: *** No rule to make target 'localmodconfig'.  Stop.

..Now settle down here I was try too make .config too
(root@ked-VirtualBox:~# ls .config
.config)

what should i do?? and about debug..

root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ls
Makefile miscdrv_rdwr.c rdwr_test_secret.c
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# ../../lkm miscdrv_rdwr
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# rmmod miscdrv_rdwr 2>/dev/null
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# sudo dmesg -C
root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# make | exit 1
strip: './miscdrv_rdwr.ko': No such file
make: *** [Makefile:99: all] Broken pipe

root@ked-VirtualBox:/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr# make
strip: './miscdrv_rdwr.ko': No such file

--- Building : KDIR=/lib/modules/5.10.60-prod01/build ARCH= CROSS_COMPILE= ccflags-y=-UDEBUG -DDYNAMIC_DEBUG_MODULE ---
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

make -C /lib/modules/5.10.60-prod01/build M=/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr modules
make[1]: Entering directory '/home/ked/lkd_kernels/debugk/linux-5.10.60'
CC [M] /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.o
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c: In function ‘open_miscdrv_rdwr’:
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c:97:2: error: implicit declaration of function ‘PRINT_CTX’ [-Werror=implicit-function-declaration]
97 | PRINT_CTX(); // displays process (or atomic) context info
| ^~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:280: /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.o] Error 1
make[1]: *** [Makefile:1822: /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr] Error 2
make[1]: Leaving directory '/home/ked/lkd_kernels/debugk/linux-5.10.60'
make: *** [Makefile:103: all] Error 2

I been setting CONFIG_DEBUG_FS_DISALLOW_MOUNT=y

should I refresh ch3/miscdrv_rdwr?

**Comment by alpahca** [comment]
Long time no see Mr.
I was get linux header well but..

                from /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c:37:
./include/linux/page-flags-layout.h:95:2: error: #error "Not enough bits in page flags"
   95 | #error "Not enough bits in page flags"
      |  ^~~~~
In file included from ./include/linux/umh.h:4,
                 from ./include/linux/kmod.h:9,
                 from ./include/linux/module.h:16,
                 from /home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c:37:
./include/linux/gfp.h:419:2: error: #error GFP_ZONES_SHIFT too large to create GFP_ZONE_TABLE integer
  419 | #error GFP_ZONES_SHIFT too large to create GFP_ZONE_TABLE integer
      |  ^~~~~
./include/linux/gfp.h: In function ‘gfp_zone’:
./include/linux/gfp.h:430:20: warning: left shift count >= width of type [-Wshift-count-overflow]
  430 |  | (OPT_ZONE_DMA32 << (___GFP_MOVABLE | ___GFP_DMA32) * GFP_ZONES_SHIFT)\
      |                    ^~
./include/linux/gfp.h:455:7: note: in expansion of macro ‘GFP_ZONE_TABLE’
  455 |  z = (GFP_ZONE_TABLE >> (bit * GFP_ZONES_SHIFT)) &
      |       ^~~~~~~~~~~~~~
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c: In function ‘open_miscdrv_rdwr’:
/home/ked/Linux-Kernel-Debugging-main/ch3/miscdrv_rdwr/miscdrv_rdwr.c:97:2: error: implicit declaration of function ‘PRINT_CTX’ [-Werror=implicit-function-declaration]
   97 |  PRINT_CTX(); // displays process (or atomic) context info
      |  ^~~~~~~~~

get back like this.
what should i do??

**Comment by alpahca** [comment]
actually..

grep ../../lkm miscdrv_rdwr /proc/dynamic_debug/control

or

grep miscdrv_rdwr /proc/dynamic_debug/control
..
