### ISSUE TITLE
Found that in 3_kprobe example using "do_sys_open" doesn't produce expected results in testing

### ISSUE THREAD

**Issue by brian-wood** [PacktPublishing/Linux-Kernel-Debugging#4]
Hi Kaiwan, 

I was running through the example for ch4/3_kprobe and found that if using "do_sys_open" it doesn't produce any resulting dmesg/journalctl messages. When I used strace with 'vim' I found it using openat(), so when I switched to using do_sys_openat2 as the kprobe_func parameter it was working as expected. Not sure if this might need to be added into the errata as a note. :-)

I'm using the 6.4.y latest stable for my testing (on Ubuntu 22.04 VM), so not sure if that might have any impact on the results. If I remember correctly I think this was also the case when I was debugging an issue back a while ago that for some reason do_sys_open would never output for me.

Your writing style and ability to convey information is great, looking forward to reading more of your books when they come out. 

Brian W.

**Comment by kaiwan** [comment]
Hi Brian,
Thanks; I noticed it too! Have mentioned it here:
https://github.com/PacktPublishing/Linux-Kernel-Debugging#updates--observations .

You did prompt me to thus edit the test.sh script therein, changing the function to be kprobed.
Thanks again!

A request, Brian: I like the way you carefully try out the code and report issues. Could you consider
doing so for the code of the LKP 2nd Edition book? The GitHub repo's here:
https://github.com/PacktPublishing/Linux-Kernel-Programming_2E . TIA.
